language: node_js   #指定使用的语言
node_js: 16
script:
  - "npm run build"
install: 
  - cabal update 
  - cabal install pandoc 
cache:              # 指定缓存模块，可选。缓存可加快编译速度。
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  repo: Lsyhprum/lsyhprum.github.io
  on:
    branch: source
  local-dir: public

branches:
  only:
    - source        #触发持续集成的分支